# Generated by Django 5.0.6 on 2024-06-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TranscendenceApp', '0002_alter_game_player1_alter_game_player1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycustomuser',
            name='wow',
            field=models.IntegerField(null=True),
        ),
    ]
