services:
  djangoapp:
    container_name: djangoapp
    build: .
    restart: always
    ports:
      - "8000:8000"
    expose:
      - "5432"
    networks:
      - net
    env_file: .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12-bullseye
    restart: always
    env_file: .env
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata: {}

networks:
  net:
    driver: bridge
    external: false
    name: djangoapp