services:
  reverse-proxy:
    container_name: reverse-proxy
    build: ./reverse-proxy
    restart: always
    ports:
      - "8080:443"
    networks:
      - net
    depends_on:
      - djangoapp
    env_file: .env

  djangoapp:
    container_name: djangoapp
    build: ./djangoapp
    restart: always
    expose:
      - "5432"
      - "8000"
    networks:
      - net
    env_file: .env
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12-bullseye
    restart: always
    env_file: .env
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata: {}

networks:
  net:
    driver: bridge
    external: false
    name: djangoapp