services:
  djangoapp:
    container_name: djangoapp
    build: .
    ports:
      - "8000:8000"
    expose:
      - "5432"
    networks:
      - net
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@django.com
      - DJANGO_SUPERUSER_PASSWORD=password
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12-bullseye
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net

volumes:
  pgdata: {}

networks:
  net:
    driver: bridge
    external: false
    name: djangoapp